import math

RESOLUTION = (480, 270)
SW = RESOLUTION[0]
SH = RESOLUTION[1]
SW2 = RESOLUTION[0]//2
SH2 = RESOLUTION[1]//2
SCALING = 2
SCREEN_RESOLUTION = (RESOLUTION[0] * SCALING, RESOLUTION[1] * SCALING)

FOV = math.radians(60)
FOV2 = FOV/2

FPS = 60

Mouse_sens = 0.001
