print("""
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@=***********=#WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWWW#********************=@WWWWWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWW=********==========*******=@WWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWW=******===================*****@WWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW#******======#==*=####=======*+***=@@WWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWW******==####*++++**########=*..:-:***=@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWW#***==*===####+++++**#########=:----*****#@WWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWW=****=====####=*++*=############========***#WWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWW#*****=*==#########################========**WWWWWWWWWWWWWWWW

WWWWWWWWWWW=#WWWWW**==#=**=############################=======*@WWWWWWWWWWWWWWW

WWWWWWWWWW=+@WWWWW*======#####################**=########======@WWWWWWWWWWWWWWW

WWWWWWWWWW=+@WWWWW#=====########++*#@#########:::*#######=====@@WWWWWWWWWWWWWWW

WWWWWWWWWW=*+@@WWWW#===##=#####+:::#=#######=*::::+####=**+=#@WWWWWWWWWWWWWWWWW

WWWWWWWWWWW#=*+=@@@@#==+++####+:::::=+*@@@#+*:::::::====*+:+@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWW@#====#@@@**+====::*+=@@=::=#+:+@@#@@@-*=**+=*+@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW**+==**-:#+------------------+==*+==+#WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW**+*===----------------------===**==+@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW#=+*===*.---------------------==*==@=@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWW==+*=*.-.-------------------:=====@@@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWW@=#===+...-----:****--------*=#@=@@WWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWW@@@##==:...----+++-------+##@@@@@WWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWW@W@@@@@@@#+-.---------*#@@@@@@@@@@WWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@#=+++++++@@@@@@@@WWWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW####=::::::*###=#@WWWWWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@####=:-::----:######@@WWWWWWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWWWWW#=**=#=##+::-----::*##=#=**=@@@WWWWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWWW@******#**=##*-------*##=**=******@@WWWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWW@******=***=@##########@#=**********@@WWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWWW=**********=#####@@@#####=**********=@WWWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW@*=********==#############=*********=*@@WWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW#*=********==#############==********=*#@WWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWWW#*==*==##=*=##############==####=**==**#@WWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWW@=**==*****==###############=******==***#WWWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWW#***=#*****==###############=******===**#@WWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWWW=*==*=*****==###@@#########==******====*=@WWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWW@***===*****==####@@@#######==******===**=@WWWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWWW=****=#*****==#####@@@@@####==******==****#@WWWWWWWWWWWWWW

WWWWWWWWWWWWWWWWWWWW@========****==##############==*****====#==#@@WWWWWWWWWWWWW
""")